#!/bin/sh


[ "$ACTION" == "ifup" ] && ([ "$DEVICE" == "eth1" ] || [ "$DEVICE" == "pppoe-wan" ] || [ "$DEVICE" == "wlan1" ] || [ "$DEVICE" == "wlan3" ] )&& {
  killall td_conflict_check
  /usr/bin/td_conflict_check
}
