#!/bin/sh /etc/rc.common

USE_PROCD=1
START=

intel_bandsteering() {
	procd_open_instance
	procd_set_param command band_steering -58 -69 5 15 3 512
	procd_set_param env LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param respawn ${respawn_retry:-0}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	enable=$((`uci get system.@system[0].bandsteering`<<2))
	[ "$enable" == "0" ] && return
	
	intel_bandsteering
}
