#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

get_nvram_val(){
        local mtdpart=$1
        local name=$2
        val=`strings /dev/$mtdpart | grep $name | awk -F "=" '{print $2}' `
        
        [ -n "$val" ] && {
                echo "$val"
        } || {
                echo  "0"
        }
}


boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/lock/procd
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	echo "[OpenWrt] do kmloader" > /dev/console
	/sbin/kmodloader
	
	[ -f /opt/intel/wave/*.tar.gz ] && {
                rm /opt/intel/wave/*.tar.gz
    	}
		
	rf1=`get_nvram_val mtdblock2 RFTestFlag`
	[ $rf1 -eq 0 ] &&{
		rf2=`get_nvram_val mtdblock3 RFTestFlag`       
		[ $rf2 -ne 0 ] && {
			logger "restore nvram from backup"
			echo "[OpenWrt] echo ubootconfigB > ubootconfigA" > /dev/console
			mtd dump /dev/mtd3 > /dev/mtdblock2
		}
	}
	[ `uci get firewall.icmp_drop` ] && {
		uci delete firewall.icmp_drop 2>/dev/null
	}


	[ ! -f /etc/config/wireless ] && {
		# compat for brcm47xx and mvebu
		echo "[OpenWrt] generate /etc/config/wireless" > /dev/console
		/sbin/wifi config
		sleep 1
	}

	/bin/config_generate
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config
}
