#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2012 OpenWrt.org

USE_PROCD=1
START=99
SERVICE_DAEMONIZE=1

start_service() {
    stop_service
    procd_open_instance httpd
    procd_set_param limits core="unlimited"
    procd_set_param respawn
    procd_set_param command /usr/sbin/httpd
    procd_close_instance
}
