#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=99
STOP=99

start(){
    /sbin/limitTemperature.sh &
	
}

stop(){
	#killall -9 limitTemperature.sh
	pid=`ps | grep limitTemperature.sh -m1|sed '/grep/d'|awk '{print $1}'`
    [ "$pid"x != "x" ]&&{
                kill -9 $pid
    }
}
