#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2012 OpenWrt.org

USE_PROCD=1
START=49
SERVICE_DAEMONIZE=1

start_service() {
    stop_service
    procd_open_instance td_flow_statistic_ctl
    procd_set_param respawn
    procd_set_param command /bin/td_flow_statistic_ctl -w
    procd_close_instance
}
