#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2012 OpenWrt.org

USE_PROCD=1
START=99
SERVICE_DAEMONIZE=1

start_service() {
    for i in $( seq 1 10)
    do
        [ -n "$(ifconfig br-lan  | grep "inet addr")" ] || sleep 1
    done
    stop_service
    procd_open_instance ucloud
    procd_set_param respawn
    procd_set_param command /bin/ucloud -l 4
    procd_close_instance
}