#!/bin/sh /etc/rc.common

USE_PROCD=1
START=10

start_service() {
	procd_open_instance
	procd_set_param command dwpald
	/etc/sh/CE_tx_power.sh 0
	procd_set_param user nwk
	procd_set_param capabilities /usr/share/capabilities/netifd_cap.json
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param respawn ${respawn_retry:-0}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	procd_open_instance
	procd_set_param command /lib/netifd/debug_post_iw_up.sh
	procd_set_param user nwk
	procd_set_param capabilities /usr/share/capabilities/netifd_cap.json
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	if [ -d /proc/net/mtlk/card0 ]
	then
		procd_open_instance
		procd_set_param user nwk
		procd_set_param capabilities /usr/share/capabilities/wlan_cap.json
		procd_set_param pseudofs_acl /usr/share/pseudofs_acl/dumphandler_pseudofs_acl.json
		procd_set_param command /opt/intel/bin/dump_handler -i 0 -f /opt/intel/wave/
		procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
	if [ -d /proc/net/mtlk/card1 ]
	then
		procd_open_instance
		procd_set_param user nwk
		procd_set_param capabilities /usr/share/capabilities/wlan_cap.json
		procd_set_param pseudofs_acl /usr/share/pseudofs_acl/dumphandler_pseudofs_acl.json
		procd_set_param command /opt/intel/bin/dump_handler -i 1 -f /opt/intel/wave/
		procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
	if [ -d /proc/net/mtlk/card2 ]
	then
		procd_open_instance
		procd_set_param user nwk
		procd_set_param capabilities /usr/share/capabilities/wlan_cap.json
		procd_set_param pseudofs_acl /usr/share/pseudofs_acl/dumphandler_pseudofs_acl.json
		procd_set_param command /opt/intel/bin/dump_handler -i 2 -f /opt/intel/wave/
		procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
	procd_open_instance
	procd_set_param user nwk
	procd_set_param command /opt/intel/bin/logserver -f mtlkroot0 -s /lib/firmware/fw_scd_file.scd
	procd_set_param env	PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin	LD_LIBRARY_PATH=/opt/intel
	procd_set_param respawn
	procd_set_param	stdout 1
	procd_set_param	stderr 1
	procd_close_instance
}
