#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

#avoid russia wan2 not dns after wan down
wan_proto=`uci get network.wan.proto`
if [ "$wan_proto" == "pptp" -o "$wan_proto" == "l2tp" ];then
    ifup wan2
fi
